# -*- coding: utf-8 -*-
"""appnb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYin09dx5_gpCEt_Ic1vgrEj-_-UoeDU
"""

import streamlit as st
import pandas as pd
import joblib

# Load the trained model
model = joblib.load("naive_bayes_model.pkl")

# Page title
st.title("USD/MYR Risk Level Classifier")
st.markdown("Predict the risk category based on macroeconomic differences")

# Input fields
features = {
    "difference_MSIA_UR_lag1": st.number_input("Change in Malaysia Unemployment Rate (lag1)", value=0.0),
    "difference_MSIA_CPI_lag1": st.number_input("Change in Malaysia CPI (lag1)", value=0.0),
    "difference_GVZ_lag1": st.number_input("Change in Gold Volatility Index (GVZ, lag1)", value=0.0),
    "difference_USA_IR_lag1": st.number_input("Change in US Interest Rate (lag1)", value=0.0),
    "difference_USA_M1_lag1": st.number_input("Change in US M1 Supply (lag1)", value=0.0),
    "difference_VIX_lag1": st.number_input("Change in VIX (Volatility Index, lag1)", value=0.0),
    "difference_MSIA_NetTrade_lag1": st.number_input("Change in Malaysia Net Trade (lag1)", value=0.0)
}

# Convert input to DataFrame
input_df = pd.DataFrame([features])

# Predict
if st.button("Predict Risk Level"):
    prediction = model.predict(input_df)[0]

    # Optional: map labels to human-readable text
    risk_map = {1: "Low Risk", 2: "Medium Risk", 3: "High Risk"}
    st.subheader("Prediction:")
    st.write(f"🧭 The predicted USD/MYR risk level is: **{risk_map.get(prediction, 'Unknown')}**")

